[features]
seeds = false
skip-lint = false
[programs.devnet]
myproject = "B1oXQn9bM35wGjMd7tcvmafhy7DHkfNUtcKZ6U9p4giL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/daoist/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.js"
